version: '3.8'

services:
  lux-in-tenebris:
    image: ghcr.io/d135-1r43/lux-in-tenebris:1.0.2
    container_name: lux-in-tenebris
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - nginx-proxy-manager

networks:
  nginx-proxy-manager:
    external: true
